#!/bin/bash
#https://answers.splunk.com/answers/625838/how-do-i-script-install-splunk-702-on-centos-7-64.html
# Splunk Installation script without  ulimit and ssl disabled
#  Do chmod 700 <filename> after you copy this script to get write permissions
# install firewalld command on server using below commands
# sudo yum install firewalld
# sudo systemctl start firewalld
# sudo systemctl enable firewalld
# sudo systemctl status firewalld
# getent passwd
# getent passwd | grep splunk
 echo
 echo '##################################################'
 echo '#                                                #'
 echo '# Welcome to the Splunk 8.4.2 auto-installer     #'
 echo '# for CentOS 7 x64.                              #'
 echo '# Last updated 02/03/2021.                       #'
 echo '# This script is for very basic Splunk UF install#'
 echo '# This will set the Splunk best practice Ulimits #'
 echo '#                                                #'
 echo '##################################################'
 echo
 echo
 #
 ##
 echo "Setting Ulimts and Disabling Transparent Huge Pages"
 ##
 #
 echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
 echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
 echo "[Unit]" > /etc/systemd/system/disable-thp.service
 echo "Description=Disable Transparent Huge Pages" >> /etc/systemd/system/disable-thp.service
 echo "" >> /etc/systemd/system/disable-thp.service
 echo "[Service]" >> /etc/systemd/system/disable-thp.service
 echo "Type=simple" >> /etc/systemd/system/disable-thp.service
 echo 'ExecStart=/bin/sh -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled && echo never > /sys/kernel/mm/transparent_hugepage/defrag"' >> /etc/systemd/system/disable-thp.service
 echo "Type=simple" >> /etc/systemd/system/disable-thp.service
 echo "" >> /etc/systemd/system/disable-thp.service
 echo "[Install]" >> /etc/systemd/system/disable-thp.service
 echo "WantedBy=multi-user.target" >> /etc/systemd/system/disable-thp.service
 systemctl daemon-reload
 systemctl start disable-thp
 systemctl enable disable-thp
 echo
 echo "Transparent Huge Pages (THP) Disabled."
 echo
 ulimit -n 64000
 ulimit -u 16000
 echo "DefaultLimitFSIZE=-1" >> /etc/systemd/system.conf
 echo "DefaultLimitNOFILE=64000" >> /etc/systemd/system.conf
 echo "DefaultLimitNPROC=16000" >> /etc/systemd/system.conf
 echo
 echo "ulimits Increased."
 echo
 #
 ##
 echo "Beginning Splunk Download and Install"
 ##
 #
 yum install wget -y
 cd /tmp
 wget -O splunkforwarder-8.2.4-87e2dda940d1-Linux-x86_64.tgz 'https://download.splunk.com/products/universalforwarder/releases/8.2.4/linux/splunkforwarder-8.2.4-87e2dda940d1-Linux-x86_64.tgz'
 echo
 echo "Splunk Universal Forwarder Downloaded."
 echo
 tar -xzvf /tmp/splunkforwarder-8.2.4-87e2dda940d1-Linux-x86_64.tgz -C /opt
 rm -f /tmp/splunkforwarder-8.2.4-87e2dda940d1-Linux-x86_64.tgz
 useradd splunk
 chown -R splunk:splunk /opt/splunkforwarder
 echo
 echo "Splunk Universal Forwarder Installed and splunk user created."
 echo
 #
 ##
 ###
 ####
 echo "Splunk booting up"
 ####
 ###
 ##
 #
 runuser -l splunk -c '/opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --auto-ports --no-prompt --seed-passwd password'
 echo "Splunk admin password is password"
 /opt/splunkforwarder/bin/splunk enable boot-start -user splunk
 runuser -l splunk -c '/opt/splunkforwarder/bin/splunk stop'
 chown root:splunk /opt/splunksplunkforwarder/etc/splunk-launch.conf
 chmod 644 /opt/splunksplunkforwarder/etc/splunk-launch.conf
 echo
 echo "Splunk test start and stop complete. Enabled Splunk to start at boot. Also, adjusted splunk-launch.conf to mitigate privilege escalation attack."
 echo
 runuser -l splunk -c '/opt/splunkforwarder/bin/splunk start'
 if [[ -f /opt/splunkforwarder/bin/splunk ]]
         then
                 echo Splunk Enterprise
                 cat /opt/splunkforwarder/etc/splunk.version | head -1
                 echo "has been installed, conflsigured, and started!"
                 echo "Visit the Splunk server using https://hostNameORip:8000 as mentioned above."
                 echo
                 echo
                 echo "                        HAPPY SPLUNKING!!!"
                 echo
                 echo
                 echo
         else
                 echo Splunk Enterprise has FAILED install!
 fi
 echo
 su - splunk
 echo
 echo "You are now the Splunk user"
 #End of File
